version: '3'
services:
  server-app:
    build: ./server_app/
    ports:
      - "8080:8080"

  db:
    image: "postgres:11"
    container_name: "postgres_database_feedr"
    environment: 
      POSTGRES_PASSWORD: abc807
      POSTGRES_USER: feedr_user
      POSTGRES_DB: feedr_db
    ports:
      - "5432:5432" # If you want to expose the db from the container
    volumes:
      - db_data:/var/lib/postgresql/data

  client-app:
    build: ./client_app/
    ports:
      - "80:80"

volumes:
  db_data: {}