version: "3.7"

services: 
  server-app:
    image: ubuntu:16.04
    volumes:
      - ./server_app/server_app.aot:/app/server_app.aot
      - ./server_app/config.yaml:/app/config.yaml
    command: sh -c "cd /app && chmod +x ./server_app.aot && ./server_app.aot --port 8080 --isolates 1"
    restart: "no"
    ports: 
      - 8080:8080
  
  db:
    image: "postgres:11"
    container_name: "postgres_database_feedr"
    environment: 
      POSTGRES_PASSWORD: abc807
      POSTGRES_USER: feedr_user
      POSTGRES_DB: feedr_db
    ports:
      - "5432:5432" # If you want to expose the db from the container
    volumes:
     - db_data:/var/lib/postgresql/data
  
  client-app:
    image: nginx:alpine
    volumes:
      - ./client_app/public/web/:/usr/share/nginx/html/
      - ./client_app/data/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  db_data: {}