version: '3'
services:
  my-app:
    build: .
    ports:
    - "80:80"

  db:
    image: "postgres:12"
    container_name: "postgres_database"
    environment: 
      POSTGRES_PASSWORD: abc807
      POSTGRES_USER: words_user
      POSTGRES_DB: words
    ports:
      - "5432:5432" # If you want to expose the db from the container
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}