name: feedr_app
description: Application to handle clients feedback.
version: 0.0.1
author: Sergey Simenshteyn <simenshteyn@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  shortid: ^0.1.1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0

dependency_overrides:
  postgres: 2.1.1