name: server_app
description: Application to handle clients feedback.
version: 0.0.1
author: Sergey Simenshteyn <simenshteyn@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 4.0.0-b1
  shortid: ^0.1.1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: 2.0.0-b1
